### ISSUE TITLE
The app is crashing on meteor v0.6

### ISSUE THREAD

**Issue by nikhildaga** [nathanfiedler/meteor-issuetracker#1]
Errors:

TypeError: Object #<Object> has no method 'require'
    at app/server/api.js:6:35
    at /var/www/meteor-issuetracker/.meteor/local/build/server/server.js:282:7
    at Array.forEach (native)
    at Function._.each._.forEach (/home/*/.meteor/tools/54fc781f89/lib/node_modules/underscore/underscore.js:79:11)
    at run (/var/www/meteor-issuetracker/.meteor/local/build/server/server.js:227:7)

**Comment by nathanfiedler** [comment]
As of 0.6.0, `__meteor_bootstrap__.require("xxxxx")` was removed and replaced by `Npm.require("xxxxx")`, which is the cause of this issue.

And, as of 0.6.4, with the upgrade of the _connect_ package to 2.7.10, the router middleware has been removed. So, no RESTful API for the time being. I may go back to implementing [collectionapi](https://github.com/crazytoad/meteor-collectionapi), [meteor-router](https://github.com/tmeasday/meteor-router), or the newer [meteor-reststop](https://github.com/gkoberger/meteor-reststop) to get this working again when I get a chance.

Also updated the code in a few other places to handle some 0.6.x changes, and it does run now in 0.6.4.1. Sorry for the 4 month wait!
